### ISSUE TITLE
Stuck on Generic Mod Manager

### ISSUE THREAD

**Issue by Yot360** [Genwald/Generic-Mod-Manager#2]
Everytime I launch it on my switch I cannot do anything on the app 
![image](https://user-images.githubusercontent.com/65982248/82952961-ef200880-9f77-11ea-87dd-8b0aa2792fd9.jpg)

**Comment by Genwald** [comment]
Yeah, pynx needs to be updated to use new libnx due to a system update that broke button input in homebrew. You can still use it by setting "enable_deprecated_hid_mitm = u8!0x1" in /atmosphere/config/system_settings.ini as a workaround that atmosphere implemented for this issue.
Alternatively, I recommend using [SimpleModManager](https://github.com/nadrino/SimpleModManager/releases) which seems to be based on GenericModManager and is actively maintained.

**Comment by Yot360** [comment]
Thanks I tried Simple Mod Manager but when I enable  a mod the mod doesn’t work on my game, any idea why. I created a mod folder and a folder with the Abel of my game and put the mods in it, everything work when I activate them but they don’t work in the game. Thanks for replying 😄
Edit: I don’t have the file you’re talking about in the atmosphere/config folder

**Comment by Yot360** [comment]
I solved it, I asked to gba temp discussion and they gave me the answer thanks for listening to me and have a great day 🙂

**Comment by Genwald** [comment]
> I don’t have the file you’re talking about in the atmosphere/config folder  

Yes, you have to copy it from config_templates or just create it yourself. Atmosphere only ships templates now so that your configs don't get overwritten by updates.

**Comment by Yot360** [comment]
> > I don’t have the file you’re talking about in the atmosphere/config folder
> 
> Yes, you have to copy it from config_templates or just create it yourself. Atmosphere only ships templates now so that your configs don't get overwritten by updates.

Ok thanks
